version: '3.9'
services:
  backend:
    build: .
    container_name: backend_app
    environment:
      - DATABASE_URL="mysql://root:rootsosecure@host.docker.internal:3306/hdmtestdev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
